name: Deploy on EC2

on: [workflow_dispatch]

jobs:
  deploy-aws-ec2:
    runs-on: ubuntu-latest
    env:
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    environment:
      name: aws-ec2
      url: http://${{ env.EC2_HOST }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Copy Files to AWS EC2
        shell: bash
        run: |
          echo "$EC2_SSH_KEY" > key.pem && chmod 400 key.pem
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
          scp -i key.pem -r _site/ "${EC2_USER}@${EC2_HOST}":'$HOME/html/'

      - name: Stamp Deployment Target
        run: |
          sed -i 's/deployment target: unknown/deployment target: AWS EC2/' _site/index.html

      - name: Deploy on AWS EC2
        shell: bash
        run: |
          # EOF is quoted so $HOME is not evaluated on client site
          ssh -i key.pem "${EC2_USER}@${EC2_HOST}" << 'EOF'
            sudo apt-get update && sudo apt-get install nginx -y
            sudo systemctl enable --now nginx
            shopt -s dotglob
            mv $HOME/html/* /var/www/html/
            shopt -u dotglob
          EOF
        
      - name: Write Multi-line Summary
        run: |
          # EOF is unqoted to access $EC2_HOST
          cat << EOF >> $GITHUB_STEP_SUMMARY
          ### 🚀 Deployment Status

          | Deployed To | ACCESS AT |
          | ----------  | --------- |
          | AWS EC2     | "http://$EC2_HOST" |
          
          **Click the URL to access application.**
          EOF
