name: Deploy on EC2

on: [workflow_dispatch]

jobs:
  deploy-aws-ec2:
    runs-on: ubuntu-latest
    env:
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_HOST: ${{ vars.EC2_HOST }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}

    environment:
      name: aws-ec2
      url: http://${{ env.EC2_HOST }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Stamp Deployment Target
        run: |
          sed -i 's/deployment target: unknown/deployment target: AWS EC2/' _site/index.html

      - name: Copy Files to AWS EC2
        shell: bash
        run: |
          echo "$EC2_SSH_KEY" > key.pem && chmod 400 key.pem
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          rsync -avz -e "ssh -T -i key.pem" _site/ "${EC2_USER}@${EC2_HOST}":html/

      - name: Deploy on AWS EC2
        shell: bash
        run: |
          # EOF is quoted so $HOME is not evaluated on client site
          ssh -T -i key.pem "${EC2_USER}@${EC2_HOST}" << 'EOF'
            if ! command -v nginx > /dev/null 2>&1; then
              sudo apt-get update && sudo apt-get install nginx -y
              sudo systemctl enable --now nginx
            fi
          sudo rsync -a --delete html/ /var/www/html/
          EOF
        
      - name: Write Multi-line Summary
        shell: bash
        run: |
          # EOF is unqoted to access $EC2_HOST
          cat << EOF >> "$GITHUB_STEP_SUMMARY"
          ### 🚀 Deployment Status

          | Deployed To | ACCESS AT |
          | ----------  | --------- |
          | AWS EC2     | [http://$EC2_HOST](http://$EC2_HOST) |
          
          **Click the URL to access application.**
          EOF
